sudo: required
dist: trusty
language: cpp


services:
  - docker

before_install:
  - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then export BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; export SLUG=$TRAVIS_PULL_REQUEST_SLUG; fi
  - if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then export BRANCH=$TRAVIS_BRANCH; export SLUG=$TRAVIS_REPO_SLUG; fi
  - docker pull dealii/dealii:v8.4.2-gcc-mpi-fulldepsmanual-debugrelease
  - docker run dealii/dealii:v8.4.2-gcc-mpi-fulldepsmanual-debugrelease /bin/sh -c "wget https://github.com/$SLUG/archive/$BRANCH.zip; unzip -q $BRANCH.zip; echo 'Branch name:'; echo $BRANCH; python phaseField-${BRANCH#v}/tests/automatic_tests/run_automatic_tests.py"

script: bash test_ci.sh
