all:


install:
	cmake phaseField/applications/singlePrecipitate_conservedAC/CMakeLists.txt
	bash install.sh

clean:
	rm phaseField/applications/singlePrecipitate_conservedAC/CMakeCache.txt
	rm phaseField/applications/singlePrecipitate_conservedAC/main

distclean: clean

.PHONY: all install clean distclean
